//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualityMonitoringSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coursework
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string BoxFileLink { get; set; }
        public bool Reviewed { get; set; }
        public int ModuleID { get; set; }
    
        public virtual Module Module { get; set; }
    }
}
